# Generated by Django 2.2.12 on 2023-03-30 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Odjel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_odjela', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pacijent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broj_zdravstvene', models.CharField(max_length=9, unique=True)),
                ('ime_pacijenta', models.CharField(max_length=50)),
                ('prezime_pacijenta', models.CharField(max_length=50)),
                ('broj_mobitela', models.CharField(max_length=10)),
                ('razlog_dolaska', models.TextField()),
                ('odjel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Odjel')),
            ],
        ),
    ]
